#스마투프 프리미엄 운영 서버
#지역 : USA-EAST (미국 서부 - 캘리포니아)
spring:
    profiles:
        active: us-dentist
    #datasource (mariaDB)
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        #미국 데이터베이스(캘리포니아)
        db-url: jdbc:log4jdbc:mariadb://smartooth-us-database.cs4boanjdk1j.us-west-1.rds.amazonaws.com/smartooth_premium
        db-username: smartooth
        db-password: smartooth509#

    loginUrl: 54.176.146.132:8090
        
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
        static-path-pattern : /static/**

        
    #메일 발송 부분은 로직은 동일, 메일 발송 HOST, ID, 비밀번호만 변경해주면 됨
    mailsendername: Smartooth KOREA
    mailusername: contact@smartooth.co
    mailpassword: lKX7ucWCMADB
  
  
    mybatis:
        configuration:
            map-underscore-to-camel-case: 'true'


    jwt:
        secretKey: tmakxntmzhfldk
        
        
    web:
        resources:
            static-locations : classpath:/static-location/

server:
    #운영 Prod (AWS) - USA
    ip: 54.176.146.132
    port: 8090

            
#---
#spring:
#    web:
#        resources:
#            add-mappings: 'true'